# Generated by Django 5.2.4 on 2025-08-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_note_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
    ]
