# Generated by Django 5.2.4 on 2025-08-06 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_offer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
