# Generated by Django 5.2.4 on 2025-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_note_created_at_offer_title_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('WYOKŃCZENIA', 'Wykńczenia'), ('REMONTY', 'Remonty'), ('PRACE ZIEMNE', 'Prace ziemne'), ('OGRODNICTWO', 'Ogrodnictwo')], default='PRACE ZIEMNE', max_length=15),
        ),
    ]
