# Generated by Django 5.2.4 on 2025-08-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_offer_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
